name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy --all-targets -- --deny warnings
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test -- --include-ignored
