name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt -- --check
      - name: Lint
        run: cargo clippy --all-targets -- --deny warnings
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs:
      - static
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test -- --include-ignored
